/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package miniproyectopoo_2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisc
 */
public class PanelUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuario
     */
    private VentanaPrincipal ventanaPrincipal;
    private VentanaInicio ventanaInicio;
    private FormularioFactura factura;
    private TablaProductosAdmin tablaProductosAdmin;

    public PanelUsuario(VentanaInicio ventanaInicio , VentanaPrincipal ventanaPrincipal,TablaProductosAdmin tablaProductosAdmin, FormularioFactura factura) {
        initComponents();
        this.ventanaInicio = ventanaInicio;
        this.ventanaPrincipal = ventanaPrincipal;
        this.factura = factura;
        this.tablaProductosAdmin = tablaProductosAdmin;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonComprar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("COMPRAR PRODUCTOS");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("SELECCIONA UN PRODUCTO DE LA TABLA");

        botonComprar.setText("COMPRAR");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonComprar)
                        .addGap(163, 163, 163)
                        .addComponent(botonVolver)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprar)
                    .addComponent(botonVolver))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE QUIERES SALIR?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        if(confirmacion == JOptionPane.YES_OPTION){
           ventanaPrincipal.dispose();
           ventanaInicio.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "SIGUE COMPRANDO!!!");
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        int confirmacionProductoSeleccionado= JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO DEL PRODUCTO A COMPRAR?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        int filaSeleccionada = tablaProductosAdmin.obtenerFila();
        DefaultTableModel modelo = tablaProductosAdmin.getModeloTabla();
        if(confirmacionProductoSeleccionado == JOptionPane.YES_OPTION){
            if(filaSeleccionada != -1){
            String codigoProducto = (String) modelo.getValueAt(filaSeleccionada, 0);
            String nombreProducto = (String) modelo.getValueAt(filaSeleccionada, 1);
            String precioProducto = (String) modelo.getValueAt(filaSeleccionada, 2);
            String impuestoProducto = (String) modelo.getValueAt(filaSeleccionada,3);
            String categoriaProducto = (String) modelo.getValueAt(filaSeleccionada, 4);
            String totalProducto = (String) modelo.getValueAt(filaSeleccionada, 5);
            
            
            factura.limpiarCamposFactura();
            
            
            factura.setCampoFacturaCodigoProducto(codigoProducto);
            factura.setCampoFacturaNombreProducto(nombreProducto);
            factura.setCampoFacturaPrecioProducto(precioProducto);
            factura.setCampoFacturaImpuestoProducto(impuestoProducto);
            factura.setCampoFacturaCategoriaProducto(categoriaProducto);
            factura.setCampoFacturaPrecioTotalProducto(totalProducto);
            factura.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "POR FAVOR SELECCIONA UNA FILA");
            }
        }else{
            JOptionPane.showMessageDialog(this, "SELECCIONADA CORRECTAMENTE EL PRODUCTO QUE QUIERES COMPRAR! :)");
        }





    }//GEN-LAST:event_botonComprarActionPerformed

//@SuppressWarnings("unchecked")
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
