package miniproyectopoo_2;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author luisc
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    private VentanaPrincipal ventanaPrincipal;
    private TablaProductosUsuario tablaProductosUsuario;
    private PanelUsuario panelUsuario;
    private TablaProductosAdmin tablaProductosAdmin;
    private PanelAdmin panelAdmin;

    public VentanaInicio() {
        initComponents();
        ventanaPrincipal = new VentanaPrincipal();
        panelAdmin = new PanelAdmin(this, ventanaPrincipal,null);
        tablaProductosAdmin = new TablaProductosAdmin(panelAdmin);
        panelAdmin.setTablaProductosAdmin(tablaProductosAdmin);
        tablaProductosUsuario = new TablaProductosUsuario();
        panelUsuario = new PanelUsuario(this, ventanaPrincipal);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonContinuar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAyuda = new javax.swing.JMenu();
        menuItemAcercaDe = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuItemContacto = new javax.swing.JMenuItem();
        menuItemSoporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        botonContinuar.setText("CONTINUAR");
        botonContinuar.setFocusable(false);
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.setFocusable(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel1.setText("¡BIENVENIDO!");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("TIENDA VIRTUAL TECNOLOGICA");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("PARA CONOCER NUESTROS PRODUCTOS, DALE CLICK AL BOTON CONTINUAR!!");

        jMenuBar1.setFocusable(false);

        menuAyuda.setText("Ayuda");

        menuItemAcercaDe.setText("Acerca de...");
        menuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuItemAcercaDe);

        jMenuBar1.add(menuAyuda);

        menuInfo.setText("Info");

        menuItemContacto.setText("Contactanos");
        menuItemContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContactoActionPerformed(evt);
            }
        });
        menuInfo.add(menuItemContacto);

        menuItemSoporte.setText("Soporte");
        menuItemSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSoporteActionPerformed(evt);
            }
        });
        menuInfo.add(menuItemSoporte);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        ventanaPrincipal.setVisible(true);
        ventanaPrincipal.cambiarPanelContenedor1(tablaProductosUsuario);
        ventanaPrincipal.cambiarPanelContenedor2(panelUsuario);
        this.dispose();
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_A) {
            ventanaPrincipal.setVisible(true);
            ventanaPrincipal.cambiarPanelContenedor1(tablaProductosAdmin);
            ventanaPrincipal.cambiarPanelContenedor2(panelAdmin);
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE QUIERES SALIR DE LA APLICACION?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "SIGUE COMPRANDO! :)");
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void menuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaDeActionPerformed
        String mensaje = "SOMOS TIENDA VIRTUAL PARA COMPRAR PRODUCTOS TECNOLOGICOS\n"
                + "\n"
                + "PARA CONOCER NUESTROS PRODUCTOS, DALE CLICK AL BOTON CONTINUAR!\n"
                + "\n"
                + "TODOS NUESTROS CANALES DE AYUDA Y SOPORTE, ESTAN EN NUESTRA OPCION DE 'INFO'";
        JOptionPane.showMessageDialog(this, mensaje, "AYUDA", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_menuItemAcercaDeActionPerformed

    private void menuItemContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContactoActionPerformed
        String mensaje = "PARA COMUNICARTE CON NOSOTROS HAZLO POR ESTOS CANALES:\n"
                + "\n"
                + "FACEBOOK: tiendavirtualluisito\n"
                + "\n"
                + "INSTAGRAM: @virtualtiendaluisito\n"
                + "\n"
                + "WHATSAPP: 1234556\n"
                + "\n"
                + "SI REQUIERES CUALQUIER TIPO DE AYUDA O SOPORTE, EN LA OPCION 'SOPORTE' ESTAN LOS CONTACTOS ESPECIALIZADOS";

        JOptionPane.showMessageDialog(this, mensaje, "CONTACTANOS", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_menuItemContactoActionPerformed

    private void menuItemSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSoporteActionPerformed
        String mensaje = "SI REQUIERES UN SOPORTE ESPECALIZADO O HABLAR CON UNO DE NUESTROS ASESORES, TENEMOS LOS SIGUIENTES CANALES:\n"
                + "\n"
                + "CORREO ELECTRONICO: tiendavirtualluisito@gmail.com y soportevirtualtiendaluisito@gmail.com \n "
                + "\n"
                + "WHATSAPP: 098765431\n"
                + "\n"
                + "POR ESTOS CANALES NUESTROS ASESORES ESTARAN DISPONIBLES ANTE CUALQUIER DUDA O INQUIETUD!";

        JOptionPane.showMessageDialog(this, mensaje, "SOPORTE", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_menuItemSoporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemContacto;
    private javax.swing.JMenuItem menuItemSoporte;
    // End of variables declaration//GEN-END:variables
}
